// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIVG34wPn_5eC4Szl7q5LVqgAzi2HfPH8',
    appId: '1:825115738922:web:22350b6676743768051453',
    messagingSenderId: '825115738922',
    projectId: 'flash-chat-53e1c',
    authDomain: 'flash-chat-53e1c.firebaseapp.com',
    storageBucket: 'flash-chat-53e1c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBM4KpeyXFk0z8xGy_xmhv2fDOEfMe0txk',
    appId: '1:825115738922:android:e6024c897deaabe1051453',
    messagingSenderId: '825115738922',
    projectId: 'flash-chat-53e1c',
    storageBucket: 'flash-chat-53e1c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCy3YXMa5fmf_5mQSxEgyYYXdCfQY1ICsU',
    appId: '1:825115738922:ios:a9603948d05cf853051453',
    messagingSenderId: '825115738922',
    projectId: 'flash-chat-53e1c',
    storageBucket: 'flash-chat-53e1c.firebasestorage.app',
    iosBundleId: 'com.example.flashChatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCy3YXMa5fmf_5mQSxEgyYYXdCfQY1ICsU',
    appId: '1:825115738922:ios:a9603948d05cf853051453',
    messagingSenderId: '825115738922',
    projectId: 'flash-chat-53e1c',
    storageBucket: 'flash-chat-53e1c.firebasestorage.app',
    iosBundleId: 'com.example.flashChatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDIVG34wPn_5eC4Szl7q5LVqgAzi2HfPH8',
    appId: '1:825115738922:web:94698c4344934574051453',
    messagingSenderId: '825115738922',
    projectId: 'flash-chat-53e1c',
    authDomain: 'flash-chat-53e1c.firebaseapp.com',
    storageBucket: 'flash-chat-53e1c.firebasestorage.app',
  );
}
